hiscli/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hiscliapp/', include('hiscliapp.urls')),
    path('graphql/',csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

hiscliapp/urls.py
 # -- coding: utf-8 --
from django.urls import path
from django.conf.urls import url, include

from django.urls import reverse_lazy

from django.conf import settings
from django.conf.urls.static import static
from .viewlogin import user_login, user_logout
#veterinaria
from .viewvetduenio import VetDuenioCrear, VetDuenioBorrar, VetDuenioDetalle, VetDuenioListar, VetDuenioModificar
#mascotas del dueño:
from .viewvetduenio import VetDuenioMascotasDetalle

from .view_duenio_mascota import admin_vetmascota
from .view_vetmascota_vetconsulta import admin_vetconsulta
from .viewvetraza import VetRazaCrear, VetRazaBorrar, VetRazaDetalle, VetRazaListar, VetRazaModificar
from .viewvetmascota import VetMascotaListar, VetMascotaCrear, VetMascotaModificar, VetMascotaBorrar, VetMascotaDetalle
from .viewvetconsulta import VetConsultaCrear, VetConsultaModificar, VetConsultaBorrar
from .view_ajax_localidades import ajax_lista_paises, ajax_lista_provincias, ajax_lista_localidades
from .viewlocalidad_prompt import LocalidadPrompt
#autogestion. alta de clínica
from .viewsolal import SolicitarAltaClinicaCrear
#autogestion. confirmar direcciòn de mail
from .view_usuario_confirmar_mail import usuario_confirmar_mail

from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views#registración

from .view_crear_clinica import crear_clinica

app_name="hiscliapp" #namespace


urlpatterns = [
    #Registración
    #https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html
    #url('^', include('django.contrib.auth.urls')),  
    #url(r'^', include('django.contrib.auth.urls')),
    #path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    #path('password-reset/<uidb64>/<token>/', empty_view, name='password_reset_confirm'),
    #url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'), 

    #resuelto:
    #https://stackoverflow.com/questions/47033030/reverse-for-password-reset-done-not-found-password-reset-done-is-not-a-vali
    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url = reverse_lazy('hiscliapp:password_reset_done')
    ), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url = reverse_lazy('hiscliapp:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    #autogestion. alta de clínica
    path('altaclinica/', SolicitarAltaClinicaCrear.as_view(), name='ag_alta_clinica'),
    path('crear_clinica/', crear_clinica, name='ag_crear_clinica'),

    #confirmar mail del usuario
    path('usuario_confirmar_mail/<str:cloudvet_token>/', usuario_confirmar_mail, name='usuario_confirmar_mail'),

    #Login y logout
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),    
    #veterinaria
    #dueño
    url(r'^vetduenio/$', login_required(VetDuenioListar.as_view()), name='vetduenio_listar'),
    url(r'^vetduenio/crear/$', login_required(VetDuenioCrear.as_view()), name='vetduenio_crear'),
    url(r'^vetduenio/(?P<pk>\d+)/$', login_required(VetDuenioDetalle.as_view()), name='vetduenio_detalle'),
    #nuevo diseño plano
    url(r'^vetduenio/mascotas/(?P<pk>\d+)/$', login_required(VetDuenioMascotasDetalle.as_view()), name='vetduenio_mascotas'),

    url(r'^vetduenio/(?P<pk>\d+)/modificar/$', login_required(VetDuenioModificar.as_view()), name='vetduenio_modificar'),
    url(r'^vetduenio/(?P<pk>\d+)/borrar/$', login_required(VetDuenioBorrar.as_view()), name='vetduenio_borrar'), 
    url(r'^vetduenio/(?P<pk>\d+)/vetmascota$', login_required(admin_vetmascota.as_view()), name='vetduenio_vetmascota'), 
    url(r'^vetmascota/(?P<pk>\d+)/vetconsulta$', login_required(admin_vetconsulta.as_view()), name='vetmascota_vetconsulta'), 
    #raza
    path('vetraza/', VetRazaListar.as_view(), name='vetraza_listar'),
    path('vetraza/crear/', login_required(VetRazaCrear.as_view()), name='vetraza_crear'),
    path('vetraza/<int:pk>/', login_required(VetRazaDetalle.as_view()), name='vetraza_detalle'),
    path('vetraza/<int:pk>/modificar/', login_required(VetRazaModificar.as_view()), name='vetraza_modificar'),
    path('vetraza/<int:pk>/borrar/', login_required(VetRazaBorrar.as_view()), name='vetraza_borrar'), 
    #mascota
    path('vetmascota/', login_required(VetMascotaListar.as_view()), name='vetmascota_listar'),
    path('vetmascota/crear/duenio/<int:vetduenio_id>/', login_required(VetMascotaCrear.as_view()), name='vetmascota_crear'),
    path('vetmascota/<int:pk>/modificar/', login_required(VetMascotaModificar.as_view()), name='vetmascota_modificar'),
    path('vetmascota/<int:pk>/borrar/', login_required(VetMascotaBorrar.as_view()), name='vetmascota_borrar'),
    path('vetmascota/<int:pk>/', login_required(VetMascotaDetalle.as_view()), name='vetmascota_detalle'),
    #consulta
    path('vetconsulta/crear/mascota/<int:vetmascota_id>/', login_required(VetConsultaCrear.as_view()), name='vetconsulta_crear'),
    path('vetconsulta/<int:pk>/modificar/', login_required(VetConsultaModificar.as_view()), name='vetconsulta_modificar'),
    path('vetconsulta/<int:pk>/borrar/', login_required(VetConsultaBorrar.as_view()), name='vetconsulta_borrar'),


    #ajax localidades
    url(r'^ajax/paises/$', login_required(ajax_lista_paises), name= 'ajax_paises'),
    url(r'^ajax/(?P<id_pais>\d+)/provincias/$', login_required(ajax_lista_provincias), name= 'ajax_provincias'),
    url(r'^ajax/(?P<id_provincia>\d+)/localidades/$', login_required(ajax_lista_localidades), name= 'ajax_localidades'),
    url(r'^localidadprompt/$', LocalidadPrompt.as_view(), name='localidad_prompt'),    

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/marco.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
    <head>

  		  <!--<meta charset="utf-8">-->
				<meta charset="utf-8">
				<meta http-equiv="content-language">
		
				<!-- Required meta tags -->
				<meta charset="utf-8">
				<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
				<!-- Bootstrap CSS -->
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
				<!--Fontawesome CDN-->
				<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
				<!-- Custom styles for this template -->
				<link rel="stylesheet" href="{% static 'css/marco.css' %}">
				<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
				<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment-with-locales.min.js"></script>			

				<title>Historia Cl&iacute;nica Veterinaria</title>

				
    	  <!-- Global site tag (gtag.js) - Google Analytics 
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-114902659-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114902659-1');
</script>
-->

    </head>
    <body>
		<!-- logo y cerrar sesion -->
	
		<nav class="navbar navbar-expand-lg navbar-light bg-light">

			
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
				  <ul class="navbar-nav">
					<li class="nav-item">
					  <a class="nav-link text-dark" href="{% url "hiscliapp:vetduenio_listar"  %}">Propietarios</a>
					</li>
					<li class="nav-item">
					  <a class="nav-link text-dark" href="{% url "hiscliapp:vetmascota_listar"  %}">Mascotas</a>
					</li>
					<li class="nav-item">
					  <a class="nav-link text-dark" href="{% url "hiscliapp:vetraza_listar"  %}">Razas</a>
					</li>
					<li class="nav-item">
							<a class="nav-link text-dark" href="{% url "hiscliapp:logout"  %}">Salir</a>
				    </li>

 				    <!--
					<li class="nav-item">
					  <a class="nav-link disabled" href="#">Disabled</a>
					</li>
					-->
				  </ul>
				</div>
				<div class="navbar-header text-dark">
						<p >usuario: <strong>{{ user.username }}</strong>   cl&iacute;nica: <strong>{{request.session.clinica_nombre}}</strong>
						{{request.session.clinica_modo_pago}}
						{% if request.session.clinica_modo_pago == 'FREE'  %}
							(Finaliza el {{request.session.clinica_fin_modo_free }})
							{% if request.session.clinica_habilitada == 'rd_verdadero'  %}
								Clínica habilitada
							{% else %}    
								Clínica inhabilitada
							{% endif %}    
						{% endif %}    


						
				</div>	
				<!-- 
				<div class="col-xs-3 col-md-1">	
					<a href="{% url "hiscliapp:vetduenio_listar"  %}">
					<img class="img-responsive" width="50"
					src= "/hiscliapp{{ MEDIA_URL }}{{request.session.clinica_imagen}}" alt="Logotipo de historia clinica"></a>
				</div>				
				-->
			  </nav>
		
    <div class= "container-fluid">
	<div class="row">
		<div class="col-xs-12 col-md-12">		


		</div>

	</div>		
  	<div class="row">
	  <div class="col-xs-4 col-md-2">	<!-- +col menu -->	
		
	  </div> <!-- -col menu -->
      <div class="col-xs-5 col-md-5">	<!-- +col usuario -->
		  
		  </p>
		  </li>

	  </div>
    </div> <!-- row -->
  	<div class="row"> 
	<div class= "container-fluid">
	<div class="row"> 	
      {% block content %}{% endblock content %}
    </div>
    </div>
    </div>
    
    </div>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>    
    
	</body>
</html>

templates/marco_historiaclinicahumanos.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
    <head>
        <title>Historia Clinica</title>
  		  <!--<meta charset="utf-8">-->
  		  <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
		    <link href='//fonts.googleapis.com/css?family=Dosis:500&effect=outline' rel='stylesheet' type='text/css'>

        <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    		<script src="{% static 'js/locales/bootstrap-datepicker.es.js'%}" charset="UTF-8"></script>
    	  <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
    <style>
      .row-bordered:after {
		  content: "";
		  display: block;
		  border-bottom: 1px solid #ccc;
		  margin: 0 15px;
	  }
    </style>

    </head>
    <body>
		<!-- logo y cerrar sesion -->
    <div class= "container">
  	<div class="row">
      <div class="col-xs-5 col-md-2">	<!-- +col menu -->	
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menú<span class="caret"></span></a>
          
          <ul class="dropdown-menu">
			<li><a href="{% url "hiscliapp:paciente_listar"  %}">Pacientes</a></li>
            <li><a href="{% url "hiscliapp:logout"  %}">Salir</a></li>
          </ul>
        </li>
      </ul>	  
	  </div> <!-- -col menu -->
      <div class="col-xs-5 col-md-2">	<!-- +col usuario -->
		  <p>usuario: <strong>{{ user.username }}</strong></p></li>
	  </div>
      <div class="col-xs-2 col-md-1">	<!-- +col logo -->
	    <a href="{% url "hiscliapp:paciente_listar"  %}"><img class="img-responsive" src= "{% static "images/logo_historia_clinica.png"%}" alt="Logotipo de historia clinica"></a>
	  </div>
    </div> <!-- row -->
  	<div class="row"> 
	<div class= "container">
	<div class="row"> 	
      {% block content %}{% endblock content %}
    </div>
    </div>
    </div>
    
    </div>
    
	</body>
</html>

templates/marco_prompt.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
    <head>

  		  <!--<meta charset="utf-8">-->
				<meta charset="utf-8">
				<meta http-equiv="content-language">
		
				<!-- Required meta tags -->
				<meta charset="utf-8">
				<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
				<!-- Bootstrap CSS -->
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
				<!--Fontawesome CDN-->
				<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
				<!-- Custom styles for this template -->
				<link rel="stylesheet" href="{% static 'css/marco.css' %}">
				<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
				<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment-with-locales.min.js"></script>			

				<title>Historia Cl&iacute;nica Veterinaria</title>

				
    	  <!-- Global site tag (gtag.js) - Google Analytics 
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-114902659-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114902659-1');
</script>
-->

  </head>
<body>
<!-- logo y cerrar sesion -->
<div class= "container-fluid">
	<div class="row"> 	
      {% block content %}{% endblock content %}
  </div>
</div>

	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>    
    
	</body>
</html>