hiscli/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hiscliapp/', include('hiscliapp.urls')),
    path('graphql/',csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

hiscliapp/urls.py
 # -- coding: utf-8 --
from django.urls import path
from django.conf.urls import url, include

from django.urls import reverse_lazy

from django.conf import settings
from django.conf.urls.static import static
from .viewlogin import user_login, user_logout
#veterinaria
from .viewvetduenio import VetDuenioCrear, VetDuenioBorrar, VetDuenioDetalle, VetDuenioListar, VetDuenioModificar
#mascotas del dueño:
from .viewvetduenio import VetDuenioMascotasDetalle

from .view_duenio_mascota import admin_vetmascota
from .view_vetmascota_vetconsulta import admin_vetconsulta
from .viewvetraza import VetRazaCrear, VetRazaBorrar, VetRazaDetalle, VetRazaListar, VetRazaModificar
from .viewvetmascota import VetMascotaListar, VetMascotaCrear, VetMascotaModificar, VetMascotaBorrar, VetMascotaDetalle
from .viewvetconsulta import VetConsultaCrear, VetConsultaModificar, VetConsultaBorrar
from .view_ajax_localidades import ajax_lista_paises, ajax_lista_provincias, ajax_lista_localidades
from .viewlocalidad_prompt import LocalidadPrompt
#autogestion. alta de clínica
from .viewsolal import SolicitarAltaClinicaCrear
#autogestion. confirmar direcciòn de mail
from .view_usuario_confirmar_mail import usuario_confirmar_mail

from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views#registración

from .view_crear_clinica import crear_clinica

app_name="hiscliapp" #namespace


urlpatterns = [
    #Registración
    #https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html
    #url('^', include('django.contrib.auth.urls')),  
    #url(r'^', include('django.contrib.auth.urls')),
    #path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    #path('password-reset/<uidb64>/<token>/', empty_view, name='password_reset_confirm'),
    #url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'), 

    #resuelto:
    #https://stackoverflow.com/questions/47033030/reverse-for-password-reset-done-not-found-password-reset-done-is-not-a-vali
    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url = reverse_lazy('hiscliapp:password_reset_done')
    ), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url = reverse_lazy('hiscliapp:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    #autogestion. alta de clínica
    path('altaclinica/', SolicitarAltaClinicaCrear.as_view(), name='ag_alta_clinica'),
    path('crear_clinica/', crear_clinica, name='ag_crear_clinica'),

    #confirmar mail del usuario
    path('usuario_confirmar_mail/<str:cloudvet_token>/', usuario_confirmar_mail, name='usuario_confirmar_mail'),

    #Login y logout
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),    
    #veterinaria
    #dueño
    url(r'^vetduenio/$', login_required(VetDuenioListar.as_view()), name='vetduenio_listar'),
    url(r'^vetduenio/crear/$', login_required(VetDuenioCrear.as_view()), name='vetduenio_crear'),
    url(r'^vetduenio/(?P<pk>\d+)/$', login_required(VetDuenioDetalle.as_view()), name='vetduenio_detalle'),
    #nuevo diseño plano
    url(r'^vetduenio/mascotas/(?P<pk>\d+)/$', login_required(VetDuenioMascotasDetalle.as_view()), name='vetduenio_mascotas'),

    url(r'^vetduenio/(?P<pk>\d+)/modificar/$', login_required(VetDuenioModificar.as_view()), name='vetduenio_modificar'),
    url(r'^vetduenio/(?P<pk>\d+)/borrar/$', login_required(VetDuenioBorrar.as_view()), name='vetduenio_borrar'), 
    url(r'^vetduenio/(?P<pk>\d+)/vetmascota$', login_required(admin_vetmascota.as_view()), name='vetduenio_vetmascota'), 
    url(r'^vetmascota/(?P<pk>\d+)/vetconsulta$', login_required(admin_vetconsulta.as_view()), name='vetmascota_vetconsulta'), 
    #raza
    path('vetraza/', VetRazaListar.as_view(), name='vetraza_listar'),
    path('vetraza/crear/', login_required(VetRazaCrear.as_view()), name='vetraza_crear'),
    path('vetraza/<int:pk>/', login_required(VetRazaDetalle.as_view()), name='vetraza_detalle'),
    path('vetraza/<int:pk>/modificar/', login_required(VetRazaModificar.as_view()), name='vetraza_modificar'),
    path('vetraza/<int:pk>/borrar/', login_required(VetRazaBorrar.as_view()), name='vetraza_borrar'), 
    #mascota
    path('vetmascota/', login_required(VetMascotaListar.as_view()), name='vetmascota_listar'),
    path('vetmascota/crear/duenio/<int:vetduenio_id>/', login_required(VetMascotaCrear.as_view()), name='vetmascota_crear'),
    path('vetmascota/<int:pk>/modificar/', login_required(VetMascotaModificar.as_view()), name='vetmascota_modificar'),
    path('vetmascota/<int:pk>/borrar/', login_required(VetMascotaBorrar.as_view()), name='vetmascota_borrar'),
    path('vetmascota/<int:pk>/', login_required(VetMascotaDetalle.as_view()), name='vetmascota_detalle'),
    #consulta
    path('vetconsulta/crear/mascota/<int:vetmascota_id>/', login_required(VetConsultaCrear.as_view()), name='vetconsulta_crear'),
    path('vetconsulta/<int:pk>/modificar/', login_required(VetConsultaModificar.as_view()), name='vetconsulta_modificar'),
    path('vetconsulta/<int:pk>/borrar/', login_required(VetConsultaBorrar.as_view()), name='vetconsulta_borrar'),


    #ajax localidades
    url(r'^ajax/paises/$', login_required(ajax_lista_paises), name= 'ajax_paises'),
    url(r'^ajax/(?P<id_pais>\d+)/provincias/$', login_required(ajax_lista_provincias), name= 'ajax_provincias'),
    url(r'^ajax/(?P<id_provincia>\d+)/localidades/$', login_required(ajax_lista_localidades), name= 'ajax_localidades'),
    url(r'^localidadprompt/$', LocalidadPrompt.as_view(), name='localidad_prompt'),    

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

hiscliapp/models.py
# -- coding: utf-8 --
from django.db import models
from datetime import date, time, datetime, timedelta

from django.db.models.query import QuerySet
from django.core.validators import RegexValidator
from django.forms import ValidationError 
from django.db.models import Max
from crum import get_current_user
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User
from django.db.models import Q

alphanumeric_validator = RegexValidator(r'^[0-9a-zA-Z]*$', 'Son permitidos solo caracteres alfanuméricos')
numeric_validator = RegexValidator(r'^[0-9]*$', 'Son permitidos solo caracteres numéricos')

class Numerador (models.Model):
	nombre = models.CharField(max_length=30, blank='true',unique=True)
	ultimo_valor = models.IntegerField(default=0)
	def __str__(self):
		return self.nombre

def sigNumero(nombreNumerador):
	try:
		n = Numerador.objects.get(nombre=nombreNumerador)
	except Numerador.DoesNotExist:
		#Si no existe en la BD, lo creo
		n = Numerador(nombre=nombreNumerador, ultimo_valor = 1)
		n.save()
		return n.ultimo_valor
	else:
		#si existe, incremento el valor, lo guardo y lo retorno
		n.ultimo_valor += 1
		n.save()
		return n.ultimo_valor

def completarConCeros( numero, longitud):
	numerotxt = str(numero)
	return numerotxt.zfill(longitud)

class PropietarioMixin(object):
    """
    Mixin providing a dispatch overload that checks object ownership. is_staff and is_supervisor
    are considered object owners as well. This mixin must be loaded before any class based views
    are loaded for example class SomeView(OwnershipMixin, ListView)
    """
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs
        # we need to manually "wake up" self.request.user which is still a SimpleLazyObject at this point
        # and manually obtain this object's owner information.
        current_user = get_current_user() # self.request.user._wrapped if hasattr(self.request.user, '_wrapped') else self.request.user
        #object_owner = getattr(self.get_object(), 'creado_por')
        
        self.object = self.get_object()
        object_id_clinica =  self.object.id_clinica()
        
        print(self.object)
        print(object_id_clinica)
        #la clinica del usuario esta en la sesion
        if 'clinica' not in self.request.session:
            id_clinica = 0
        else:
            id_clinica = int(self.request.session['clinica'])        
        
        #if current_user != object_owner and not current_user.is_superuser and not current_user.is_staff:
        #    raise PermissionDenied
        
        if id_clinica != object_id_clinica and not current_user.is_superuser and not current_user.is_staff:
            raise PermissionDenied
        return super(PropietarioMixin, self).dispatch(request, *args, **kwargs)

class Pais (models.Model):
    nombre = models.CharField('Nombre del país', max_length= 50)
    prefijo_telefonico = models.CharField('Prefijo telefónico (incluido el +)', max_length= 4) 
    def __str__(self):
        return self.nombre
    class Meta:
        verbose_name="País"
        verbose_name_plural="Paises"

class Provincia (models.Model):
    nombre = models.CharField('Nombre de la provincia', max_length= 50)
    pais = models.ForeignKey(Pais, verbose_name='País', on_delete = models.PROTECT)
    def __str__(self):
        return self.pais.prefijo_telefonico +'-'+ self.nombre

class Localidad (models.Model):
    nombre = models.CharField('Nombre de la localidad', max_length= 50)
    provincia = models.ForeignKey(Provincia, verbose_name='Provincia', on_delete = models.PROTECT)
    def __str__(self):
        return self.nombre +'. '+self.provincia.nombre
    class Meta:
        verbose_name="Localidad"
        verbose_name_plural="Localidades"

class TipoDocumento (models.Model):
    nombre = models.CharField('Nombre del tipo de documento', max_length= 20) #Ejemplo AR-DNI
    pais = models.ForeignKey(Pais, verbose_name='País', on_delete = models.PROTECT)
    def __str__(self):
        #return self.pais.prefijo_telefonico +'-'+self.nombre
        return self.nombre
    class Meta:
        verbose_name="Tipo de documento"
        verbose_name_plural="Tipos de documento"

class Persona (models.Model):
    apellido = models.CharField('Apellido', max_length= 128)
    nombres = models.CharField('Nombres', max_length= 128)
    #tipo_documento = models.ForeignKey(TipoDocumento, verbose_name='Tipo de documento', on_delete = models.PROTECT, blank=True, null=True, default=None)
    #numero_documento = models.CharField('Número de documento', max_length= 15, blank='true', validators=[numeric_validator]) #sólo números
    #localidad = models.ForeignKey(Localidad, verbose_name='Localidad', on_delete = models.PROTECT)
    domicilio = models.CharField('Domicilio', max_length= 128)
    celular_numero = models.CharField('Número de celular', max_length= 30,null='true', blank='true')
    email = models.EmailField('dirección de e-mail',null='true', blank='true')
    #twitter = models.CharField('cuenta de twitter', max_length= 50,null='true', blank='true')
    #fecha_nacimiento = models.DateField('dia y mes de cumpleaños', default=date.today)
    class Meta:
        verbose_name="Persona"
        verbose_name_plural="Personas"

#----veterinaria

class VetClinica (models.Model):
    MODO_FREE = 'FREE' # $0
    MODO_STARTER = 'STARTER' # $3 por 6 meses
    MODO_STANDARD = 'STANDARD' #5 por mes 
    MODO_PREMIUM = 'PREMIUM' # $8 por mes, incluye informe estadístico trimestral
    MODO_PAGO = (
        (MODO_FREE, 'Modo Free'),
        (MODO_STARTER, 'Modo Starter'),
        (MODO_STANDARD, 'Modo Standard'),
        (MODO_PREMIUM, 'Modo Premium'),
    )
    nombre = models.CharField('Nombre', max_length= 128)
    imagen = models.ImageField(upload_to = 'consultas/%Y/%m/%d/', default='consultas/vacio/imagenvacia.jpg')
    fecha_alta = models.DateField('Fecha de alta', default= date.today, null='true', blank='true')
    fecha_fin_free = models.DateField('Fin del modo Free', default=date.today, null='true', blank='true')
    modo_pago = models.CharField('Modo de pago',max_length=8, choices=MODO_PAGO)
    fecha_inicio = models.DateField('Fecha de alta', default=date.today, null='true', blank='true')
    def __str__(self):
        return self.nombre
        		
    class Meta:
        verbose_name="Clínica veterinaria"
        verbose_name_plural="Clínicas veterinarias"	

class VetPersonal (models.Model):
    usuario = models.ForeignKey(User, on_delete = models.PROTECT) 
    clinica = models.ForeignKey(VetClinica, verbose_name='Clínica', on_delete = models.PROTECT, blank=True, null=True, default=None)
    email = models.EmailField('e-mail',blank=True, null=True, default=None)
    
    def __str__(self):
        return self.usuario.get_full_name()#self.usuario.first_name
        		
    class Meta:
        verbose_name="Personal"
        verbose_name_plural="Personal"	

    def save(self, *args, **kwargs):        
        if not self.pk: #si no tiene pk, es insert
            id_actual=0
        else:
            id_actual= self.pk
        
        if VetPersonal.objects.filter(email = self.email).exclude(id = id_actual).exists():
            #para debug
            if self.email != '<redigi>[una cuenta de prueba]@gmail.com@gmail.com':
                raise ValidationError('La dirección de email pertenece a otro usuario. Intente con otra dirección de email')

        super(VetPersonal, self).save(*args, **kwargs)

class VetDuenio (Persona):
    codigo = models.CharField('Código',max_length=10,blank='true') #autoincremental	
    observaciones = models.TextField('Observaciones', max_length= 528 )
    creado = models.DateTimeField(auto_now_add=True, blank= True)
    creado_por = models.ForeignKey('auth.User', related_name= 'Propietario_creado_por', blank=True, null=True, default=None,on_delete = models.PROTECT)
    modificado = models.DateTimeField(auto_now=True, blank = True)
    modificado_por = models.ForeignKey('auth.User', related_name= 'Propietario_modificado_por',blank=True, null=True, default=None,on_delete = models.PROTECT)
    ultima_mascota = models.IntegerField(default=0)
    clinica = models.ForeignKey(VetClinica, related_name= 'Propietario_pertenece_a',blank=True, null=True, default=None,on_delete = models.PROTECT)
    def save(self, *args, **kwargs):
        usuario = get_current_user()
        if usuario and not usuario.pk:
            usuario = None
        #el usuario vacio se utiliza en la migración, si está vacio dejo avanzar y lo completo luego
        if usuario:
            if not self.pk: #si todavía no tiene pk, es insert
                self.codigo = completarConCeros( sigNumero('NUMPROPIETARIO'), 5) #asigno el numerador actual dentro de la campaña			
                self.creado_por = usuario
                #asocio al propietario con la clinica del usuario logueado
                personal_del_usuario = VetPersonal.objects.get( usuario = usuario) #busco al personal asociado al usuario
                self.clinica = personal_del_usuario.clinica #asigno la clinica, para visibilida
                
                #self.ultima_consulta = self.creado.date() #la última consulta coincide con la creación
            self.modificado_por = usuario #cada vez que se modifica, o al insertar 
        #Paso a mayúscula la primera letra de cada palabra       
        self.apellido = self.apellido.title() 
        self.nombres = self.nombres.title()
        super(VetDuenio, self).save(*args, **kwargs)
    def __str__(self):
        return self.apellido +', '+ self.nombres
    class Meta:
        verbose_name = 'Propietario'
    def delete(self, *args, **kwargs):
        if VetMascota.objects.filter(duenio__pk = self.pk).exists():
            raise ValidationError('El propietario tiene mascotas cargadas.')
        super(VetDuenio, self).delete(*args, **kwargs)
    def id_clinica(self):

hiscliapp/views.py
from django.shortcuts import render

# Create your views here.

templates/hiscliapp/confirmar_borrado_vetmascota.html
{% extends "marco.html" %}
{% block content %}
<div class= "container" style="margin-top:1rem">
    <div class="row font-weight-bold"> 
        <h2>{{ respuesta }}</h2> 
    </div>
    <div class="row" >
        <a class="btn btn-primary" href="/hiscliapp/vetduenio/">Volver a la lista de propietarios</a>
    </div> 
</div>
{% endblock content %}

templates/hiscliapp/confirmar_borrado_vetraza.html
{% extends "marco.html" %}
{% block content %}
<div class= "container" style="margin-top:1rem">
    <div class="row font-weight-bold"> 
        <h2>{{ respuesta }}</h2> 
    </div>
    <div class="row" >
        <a class="btn btn-primary" href="{% url "hiscliapp:vetraza_listar"  %}">Volver a la lista de razas</a>
    </div>
     
</div>

{% endblock content %}

templates/hiscliapp/form_antecedentes_familiares.html
{% extends "marco.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="es">
	<head>
        <meta charset="utf-8" />
        <title>Antecedentes familiares del paciente</title>
    </head>
	<body>

     {% load crispy_forms_tags %} 
     <form method="post" action="" class="">
        
        {% crispy form   %}
        {% crispy formset formset.form.helper %}

        <input type="submit" value="Guardar los cambios" class="btn btn-primary btn-success">
        
    </form>
    
    </body>
</html>
{% endblock content %}

templates/hiscliapp/form_consulta_imagen.html
{% extends "marco.html" %}
{% block content %}


<div class="container">
    <h2>Im&aacute;genes de la consulta</h2>
    {% load crispy_forms_tags %}    
    <form method="post" action="" class="" enctype="multipart/form-data">
     
        {% crispy form   %}
        {% crispy formset formset.form.helper %}

        <input type="submit" value="Guardar los cambios" class="btn btn-primary btn-success">
        
    </form>
</div>    
{% endblock content %}

templates/hiscliapp/form_examen_fisico.html
{% extends "marco.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="es">
	<head>
        <meta charset="utf-8" />
        <title>E&aacute;xmenes f&iacute;sicos del paciente</title>
    </head>
	<body>

     {% load crispy_forms_tags %} 
     <form method="post" action="" class="">
        
        {% crispy form   %}
        {% crispy formset formset.form.helper %}

        <input type="submit" value="Guardar los cambios" class="btn btn-primary btn-success">
        
    </form>
    
    </body>
</html>
{% endblock content %}

templates/hiscliapp/form_vetmascota_vetconsulta.html
{% extends "marco.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="es">
	<head>
        <meta charset="utf-8" />
        <title>Consultas de la Mascotas</title>
    </head>
    
	<body>

     {% load crispy_forms_tags %} 
     <form method="post" action="" class="">
        
        {% crispy form   %}
        {% crispy formset formset.form.helper %}

        <input type="submit" value="Guardar los cambios" class="btn btn-success">
        
    </form>
    
    </body>
</html>
{% endblock content %}

templates/hiscliapp/paciente_detail.html
{% extends "marco.html" %}
{% block content %}
<h3>Paciente agregado/modificado correctamente</h3>

<p>Obra social: {{ paciente.obra_social.nombre}} 
    N&uacute;mero de afiliado: {{ paciente.numero_afiliado}}</p>
<p>Apellido: {{ paciente.apellido}} Nombre: {{ paciente.nombres}} </p>
<p>Tipo de documento: {{ paciente.tipo_documento}} N&uacute;mero de documento: {{ paciente.numero_documento}} </p>

<a class="btn btn-primary" href="{% url "hiscliapp:paciente_listar"  %}">Volver a la lista de pacientes</a>
{% endblock content %}

templates/hiscliapp/paciente_form.html
{% extends "marco.html" %}
{% block content %}
<div class="col-xs-12 col-md-9 col-lg-9">
{% load crispy_forms_tags %}
{% crispy form %}
</div>
{% endblock content %}

templates/hiscliapp/solicitaraltaclinica_form.html
{% extends "marco_prompt.html" %}
{% block content %}
<div class="col-xs-12 col-md-9 col-lg-9">
{% load crispy_forms_tags %}
{% crispy form %}

</div>
{% endblock content %}

templates/hiscliapp/vetconsulta_form.html
{% extends "marco.html" %}
{% block content %}
<div class="col-xs-12 col-md-9 col-lg-9">
{% load crispy_forms_tags %}
{% crispy form %}
</div>
{% endblock content %}

templates/hiscliapp/vetmascota_confirm_delete.html
{% extends "marco.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    <div class= "container" style="margin-top:1rem">
        <div class="row font-weight-bold">    
            <h3>¿Está seguro de eliminar la mascota?</h3>
            <span class ="col-12" >Código: {{ vetmascota.codigo}}</span>
            <span class ="col-12" >Nombre: {{ vetmascota.nombre}}</span>
            <span class ="col-12">Dueño: {{ vetmascota.duenio }}</span>
            <span class ="col-12" >Fecha de nacimiento: {{ vetmascota.fecha_nacimiento|date:'d/m/Y'}} </span>
            <span class ="col-12"> Especie: {{ vetmascota.get_especie_display}}</span>
            <span class ="col-12">Raza: {{ vetmascota.raza}}</span>
            <span class ="col-12">Color: {{ vetmascota.color}} </span>
            <span class ="col-12">Sexo: {{ vetmascota.get_sexo_display}} </span>
            <span class ="col-12">Última consulta: {{ vetmascota.ultima_consulta}} </span>              
        </div>
        <div class="row" >
            <input type="submit" value="Confirmar" class="btn btn-primary btn-success"/> 
            <a class="btn btn-warning" href="/hiscliapp/vetduenio/">Volver a la lista de propietarios</a>
        </div>
    </div>    	
</form>
{% endblock content %}

templates/hiscliapp/vetmascota_detail.html
{% extends "marco.html" %}
{% load static %}
{% block content %}

{% static "" as baseUrl %}

<div class= "container" style="margin-top:1rem">

    <div class="card mb-3" style= "max-width:30rem">
        <div class="card-header">
            {{ vetmascota.codigo}}. {{ vetmascota.nombre}}
            <img width =24px src="{{ baseUrl }}/images/icono_{{vetmascota.get_especie_display}}.svg"></img>
            <img width =24px src="{{ baseUrl }}/images/icono_{{vetmascota.get_sexo_display}}.svg"></img>
        </div>
        <div class="card-body">
            <span class="badge badge-info">{{ vetmascota.raza}}</span>
            <span class="badge badge-secondary">{{ vetmascota.color}}</span>
            <span class="badge badge-dark"><span class ="col-12" id="id_edad">texto edad </span></span> 
            <br/>
            Nacimiento: {{ vetmascota.fecha_nacimiento|date:'d/m/Y'}} <br/>
            Dueño: {{ vetmascota.duenio }} <br/>
        </div>
        <div class="card-footer bg-transparent border-info">
            <a class="btn btn-success" href="{% url "hiscliapp:vetmascota_modificar" vetmascota.id %}">Modificar</a>
            <a class="btn btn-warning" style="margin-left:1rem" href="/hiscliapp/vetduenio?filtro_codigo={{vetmascota.duenio.codigo}}">Volver al propietario</a>
            <a class="btn btn-danger"  style="margin-left:1rem" href="{% url "hiscliapp:vetmascota_borrar" vetmascota.id %}">Borrar</a>
        </div>
    </div>

    <div class="row font-weight-bold">
    </div>
    <!--Calculo la edad-->
    <script type="text/javascript">
        nacimiento= '{{ vetmascota.fecha_nacimiento|date:'d/m/Y'}}' ;
        moment.locale('es');
        //texto_edad= moment(nacimiento, "DD/MM/YYYY").fromNow()
        let diferencia = moment(nacimiento, "DD/MM/YYYY").diff(moment(),'milliseconds');
        let duracion = moment.duration(diferencia);
        let anios = (-1)* duracion.years();
        let meses = (-1)* duracion.months();
        let dias = (-1)*duracion.days();
        console.log(anios);
        console.log(meses);
        console.log(dias);


        let txtanios = ' años ';
        let txtmeses = ' meses ';
        let txtdias = ' días ';
        if (anios == 1) { txtanios = ' año ' };
        if (meses == 1) { txtmeses = ' mes ' };
        if (dias == 1) { txtdias = ' día ' };

        let texto_edad = anios + txtanios + 
            meses + txtmeses+ dias + txtdias
        let li_edad = $("#id_edad");
        li_edad.text(texto_edad);
    </script>    

    <div class="row" style="margin-top:1rem">

<!--Agregar consulta-->
<a title="Agregar una consulta a la mascota" href="{% url "hiscliapp:vetconsulta_crear" vetmascota.id %}" >            
    <span class="badge badge-light"> <i class="fa fa-plus" title="Agregar consulta"></i> Nueva consulta</span>
</a>

<!--Listar consultas-->
        {% for consulta in vetmascota.vetconsulta_set.all %}     
            <a title="Modificar consulta" href="{% url "hiscliapp:vetconsulta_modificar" consulta.id %}" >
             
                <div class="card mb-3" style= "max-width:30rem">
                  <div class="card-header">
                        <span class="text-dark">{{ consulta.fecha|date:'d/m/Y' }}</span>
				  </div>
				  <div class="card-body">
                    <p class="text-dark">
                    Peso:{{ consulta.peso |floatformat:2 }} Kg<br/>
                    Motivo:{{ consulta.motivo_consulta.nombre }}<br/>
                    {{ consulta.observaciones }}</p>
                  </div>
                    <div class="card-footer bg-transparent border-info">
                        <span class="text-dark">Atendió: {{ consulta.atendio }}</span>
                    </div>
                </div>
            </a>
        {% endfor %}
       
    </div>
</div>
{% endblock content %}

templates/hiscliapp/vetraza_detail.html
{% extends "marco.html" %}
{% block content %}
<h3>Raza agregada/modificada correctamente</h3>
<p>Nombre: {{ vetraza.nombre}} </p>

<a class="btn btn-primary" href="{% url "hiscliapp:vetraza_listar"  %}">Volver a la lista de razas</a>
{% endblock content %}

templates/hiscliapp/vetraza_form.html
{% extends "marco.html" %}
{% block content %}
<div class="col-xs-12 col-md-9 col-lg-9">
{% load crispy_forms_tags %}
{% crispy form %}
</div>
{% endblock content %}